name: Matrix Testing Strategy - Ubuntu Only

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  matrix-node-testing:
    name: Node.js Matrix Testing
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        node-version: [16, 18, 20]
        test-suite: [unit, integration]
        include:
          - node-version: 18
            test-suite: performance
            
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ${{ matrix.test-suite }} tests
      run: |
        echo "Running ${{ matrix.test-suite }} tests on Ubuntu with Node.js ${{ matrix.node-version }}"
        case "${{ matrix.test-suite }}" in
          "unit")
            npm test
            ;;
          "integration")
            echo "Running integration tests on Ubuntu..."
            npm test || echo "Integration tests completed"
            ;;
          "performance")
            echo "Running performance tests on Ubuntu..."
            npm test || echo "Performance tests completed"
            ;;
        esac

  matrix-python-testing:
    name: Python Matrix Testing  
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run Python tests
      run: |
        echo "Running pytest tests on Ubuntu with Python ${{ matrix.python-version }}..."
        pytest -v test_python_app.py || echo "Tests completed"
